### ISSUE TITLE
Set View Capability

### ISSUE THREAD

**Issue by hauserkristen** [SiegeEngineers/aoe2cm2#119]
Hey Hzemi!

Ive noticed alot of casters having to do a bit of overlays to get map and civ drafts on screen at the same time and some times with all the bans, not all the information fits on the screen. Im proposing we have a view for civ and map drafts to be on simplified page (just showing results (picks with steal/snipes applied) and not the specific steals/snipes/bans/etc). I have a draft of what something like this would look like.
![Search](https://github.com/SiegeEngineers/aoe2cm2/assets/102167906/6845b4e0-4fab-4711-8ff5-6fec4e634656)
![View](https://github.com/SiegeEngineers/aoe2cm2/assets/102167906/679a0c47-b655-44d0-a021-c53ee19bd936)

I was using the API (draftOptions are missing from the API for civilizations so thats why there are no images) to bypass adjusting the redux store too much. Not sure if you find this useful and if its worth polishing up and making it a feature. Curious on your thoughts?

I can always contribute in another way, wondering if you guys would be interested in migrating to RTK Query to make the whole state store and actions/reducers more readable.

**Comment by hauserkristen** [comment]
@HSZemi  forgot the tag. Let me know what you think. Feel free to reach out on discord too. #Stealth_R_Us

**Comment by HSZemi** [comment]
Hm. Ideally, and I know this is a lot more work to implement, people could do a whole succession of drafts on one page, like map draft first, then continue with civ draft. But now people have started using the new PAUSE feature to do some civ bans, then do a map draft, and then continue the civ draft. Which makes it even more complicated.

And then, having a simplifiy toggle (or changing the behaviour of the existing one) would naturally lead to what you are proposing I believe.

Regarding the missing draftOptions, the `options` property should contain either the DraftOptions, of the resolved Civilisation objects from `encodedCivilisations`.

And regarding tech choices, my biggest concern currently is migrating away from create-react-app because that still imports a bunch of ancient dependencies…

**Comment by hauserkristen** [comment]
Ahh okay.  I would like to contribute but not sure exactly what would be useful. We could migrate to RTK Query without migrating away from create-react-app, so maybe that would be useful? Unless you had an idea for a feature.

**Comment by HSZemi** [comment]
Oh, I may have phrased this ambiguously. I would very much like to ditch create-react-app. There are only few things that would bring me greater joy.
