### ISSUE TITLE
Map Drafts

### ISSUE THREAD

**Issue by HSZemi** [SiegeEngineers/aoe2cm2#27]
As a tournament organiser  
I want to create a map draft  
So players can draft maps instead of civilisations according to a ruleset assembled from the same building blocks that civilisation drafts are built with

#### Acceptance Criteria
- Users can create Map Draft presets
- Users can create and execute Map Drafts

#### Implementation Hints
- By using the aoe2map.net api ([example](https://aoe2map.net/api/collection/adc8e357-377f-49c8-acf5-f7e716483217)), we can get a set of maps with preview images without having to build a custom UI for that
- Map images might need bigger buttons than civilisation images
- Unlike civilisations, maps are not picked for one player, but for both players. There are multiple modes for that: Players might pick the maps to be played in order, or they might pick home maps, the order of which then depends on who wins which game. When home maps are picked, a layout like for the civilisation draft might be suitable, while for picking maps in the order of games, an entirely new (for aoe2cm2) layout might be in order.

**Comment by HSZemi** [comment]
There are probably two main types of map draft:

### Players pick home maps

Essentially identical to a civ draft, just that you are picking maps instead of civs

![grafik](https://user-images.githubusercontent.com/3027817/108639152-53361580-7493-11eb-88d5-cc4d1b4bb0e9.png)


### Players pick maps that will be played in order

The order is more important that who picked the map. Might also want to pre-set some maps, like Arabia for Game 1 etc.

![grafik](https://user-images.githubusercontent.com/3027817/108639172-795bb580-7493-11eb-8210-49afc20c4a61.png)


### Players pick a general map pool

Any of the two layouts work

## Map Draft Preset configuration
Preset config consists of:
- Title
- Type of layout? (see above) Maybe make that toggle-able in the UI since it's only visual
- List of maps (see below)
- Order of turns (Turns are identical to civ draft Turns: PICK/BAN/SNIPE/STEAL, with modifiers)

A map consists of:
- Name
- URL to image (we probably don't want uses to upload map images directly to the site, that only gives us storage trouble. Downside is that images used in drafts might get unavailable in the future.)
Use default placeholder image if image url is not given

Marking maps as used works differently from a civ draft. Clicking on a map should either toggle through a game number, or between unused / Name of Captain 1 / Name of Captain 2.
Maybe even make the left half toggle through game numbers and the right trough names :thinking:

**Comment by lalitpatel** [comment]
> URL to image (we probably don't want uses to upload map images directly to the site, that only gives us storage trouble. Downside is that images used in drafts might get unavailable in the future.)

For first version, we can have the list of default maps and their thumbnail on server. An admin can select the pool of Maps from the this list and can add one or more of his own (for that preset only) and then they can:
1. Either select the thumbnail of one the default maps that closely matches to the one they are using. eg ECL_Arabia can use Arabia thumbnail, Pants can use Bay thumbnail and so on. 
2. Or, use a default placeholder image. 

I believe this will cover 80% of the use cases.

**Comment by lalitpatel** [comment]
> Map presets and drafts should be stored separately from civ presets and drafts (probably in folders named "map-presets" and "map-drafts")

Since the map and civ preset are tightly linked (will be used together), I think it makes sense for a preset to have a dictionary of sub-presets eg:
```
{
    maps: { 
        ... map preset data ...
    },
    civs: {
        ... civ preset data ...
    },
}
```
This makes the preset extensible and can have one or more sub-presets depending on the tournament format. Same for drafts - each draft can have one or more sub-drafts (maps, civs etc)

This would mean that we might have to do Map and Civ drafts one after another (order agnostic) by prompting the captains to move on to the next draft after one is completed. This can also lead to some edge cases like: What happens if captains drop off after civ draft and before the map draft? The draft is discarded and they restart the draft? However, I feel after an initial learning curve for the users, they will get used to checking if a draft is a 1 step or 2 step process. 

**Existing APIs:**
We can still have the API's available to either get the combined preset or just the map or civ preset so there is backward compatibility for any other devs who are using this eg. Overlay Guy. If this number is not large then it may make sense to make a breaking change to the APIs as well.

**Comment by GrandyB** [comment]
Talking with a tournament organiser on how to do our drafting; set on aoe2cm for civ picks/bans for future tournaments and wondered if there was the equivalent for maps, but alas... here we are!

Even if it was solely map names as a starting point, would be vastly better than getting two people to hook up in DMs, remember the pool, track it themselves and report it back; can all be managed centrally.

I realise this issue is nearly a year old now, but just wanted to give my +1 to the want/need/approach.

**Comment by HSZemi** [comment]
Turns out with a bit of refactoring you can just do map drafts with custom draft options.

Options still to consider:
- custom draft layout for drafting into a common pool?
- add option to make panels bigger / non-square?

**Comment by HSZemi** [comment]
People have been map drafting since forever now. Seems alright :+1
